application: namanlab
version: 1_6
runtime: python
api_version: 1

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 )$


handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /portfolio
  static_files: content/portfolio_design.pdf
  upload: content/portfolio_design.pdf

- url: /projects
  static_files: content/portfolio_hci.pdf
  upload: content/portfolio_hci.pdf


#- url: /content/r/([^/]+)
 # static_files: content/r/\1
  #upload: content/r/([^/]+)
      
- url: /content/([^/]+)/(.*)
  static_files: content/\1/\2
  upload: content/[^/]+/.*


- url: /_ah/queue/deferred
  script: deferred.py
  login: admin

- url: /admin/.*
  script: admin.py
  login: admin

- url: /static/([^/]+)/(.*)
  static_files: themes/\1/static/\2
  upload: themes/[^/]+/static/.*

- url: /.*
  script: static.py
